#!/usr/bin/env bash
# Regenerates datamatrix-golden.txt from zint (https://zint.org.uk).
# zint is only needed to refresh the golden data, not to run the tests.
#
# Each case forces a symbol size (zint --vers) and uses digit-only data, so
# zint's encoder emits plain ASCII encodation and the output is comparable
# module for module with this package. Data leaves three codewords of
# padding so the pad sequence is covered too.
set -euo pipefail
cd "$(dirname "$0")"

# Data codewords per zint version 1-30 (24 squares, then 6 rectangles).
caps=(3 5 8 12 18 22 30 36 44 62 86 114 144 174 204 280 368 456 576 696 816 1050 1304 1558 5 10 16 22 32 49)

digits() { # deterministic pseudo-random digits
	local n=$1 x=12345 s=""
	for ((i = 0; i < n; i++)); do
		x=$(((x * 1103515245 + 12345) % 2147483648))
		s+=$(((x / 65536) % 10))
	done
	printf '%s' "$s"
}

{
	echo "# generated by gen-golden.sh with $(zint --version | head -1)"
	for v in $(seq 1 30); do
		cap=${caps[$((v - 1))]}
		n=$((cap * 2 - 6))
		((n < 1)) && n=1
		d=$(digits "$n")
		echo "case plain $v $d"
		zint -b DATAMATRIX --vers="$v" --dump -d "$d"
	done
	for g in "[01]04150000021126[17]250630[10]123456" \
		"[01]09506000134352[17]201231[10]4512[21]12345678901234"; do
		echo "case gs1 0 $g"
		zint -b DATAMATRIX --gs1 --square --dump -d "$g"
	done
} > datamatrix-golden.txt
